### ISSUE TITLE
Badge per matrix job item

### ISSUE THREAD

**Issue by gracjan** [bjfish/travis-matrix-badges#1]
Feature request:

Something like this:

```
https://travis-matrix-badges.herokuapp.com/repos/${repo_owner}/${repo_name}/branches/${branch}/${job}
```

where `job` would be an item from `matrix` in `.travis.yml`.

**Comment by vonpupp** [comment]
:+1: This would be just awesome!

**Comment by bjfish** [comment]
This was added by @tzachshabtay in #5  , thanks again.
