### ISSUE TITLE
Allow to render per-job

### ISSUE THREAD

**Issue by LuisAlejandro** [bjfish/travis-matrix-badges#10]
Hi. Is there any possibility of adding another /{job}/ component at the end of the URL so that it renders a specific job?

Thank you!

**Comment by bjfish** [comment]
Does the "Badge Per Job" option do what you are describing?
https://github.com/bjfish/travis-matrix-badges#badge-per-job

**Comment by LuisAlejandro** [comment]
Oh, yeah!

Sorry, I didn't scroll hahaha

Thanks.
